# Config file for automatic testing at travis-ci.org
os: linux
dist: bionic
language: python
python:
  - 3.9
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - tox

notifications:
  email:
    recipients:
      - sudo.karmakar@gmail.com
    on_success: change
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#github-sudiptakarmakar-algae"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change set : %{compare_url}"
      - "Build %{result}: %{build_url}"
      - "Elapsed %{elapsed_time}"
    on_success: always
    on_failure: always
