version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    dev-tests:
        docker:
            - image: circleci/python:3.9
        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: |
                      python -m pip install --user -r requirements_dev.txt
            - run:
                  name: Run Linter
                  command: |
                      mkdir -p reports/flake8
                      python -m flake8 -v --format junit-xml --output-file=reports/flake8/flake8.xml src/algae tests
            - run:
                  name: Run unit tests
                  command: |
                      mkdir -p reports/pytest
                      python -m pip install -e .
                      python -m pytest --cov=src/algae --cov-report term-missing --junitxml=reports/pytest/junit.xml --html=reports/pytest/pytest.html --self-contained-html
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
workflows:
    build:
        jobs:
            - dev-tests
