version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: run all tests
          command: python -m pytest -v
      - store_test_results:
          path: test-results
workflows:
  main:
    jobs:
      - test
